### ISSUE TITLE
PL for winning No Shares is incorrectly set to 0 at market finalization

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur-node#735] opened 2018-11-29 23:37 UTC
- Acquire No shares by selling Yes and matching it with another account
- Move time to end the market and go through reporting and the dispute period
- Finalize the market
- Unrealized PL will be 0

**Comment by adrake33** [comment] 2018-11-30 23:45
Dupe of https://github.com/AugurProject/augur/issues/263

**Closed by adrake33** 2018-11-30 23:45 UTC
Labels: Priority: Very High, Release 1.9.0, bug, v1
